language: java
jdk:
  - openjdk8
  - openjdk11
env:
  - SAMPLE=cxf
  - SAMPLE=spock
  - SAMPLE=xmlunit
script: "cd $SAMPLE && mvn --errors --batch-mode clean verify"
notifications:
    email:
        - martin.hofmannsobik@1und1.de
