name: test

# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  verify_job:
    runs-on: ubuntu-latest
    container:
      image:  maven:3-jdk-8-slim
    steps:
      - uses: actions/checkout@master
      - run: mvn --batch-mode --show-version -f spock test
      - uses: docker://python:3-slim
        with:
          args: ls -l && pwd && ls -l /
      - uses: docker://python:3-slim
        with:
          args: python3 -c "import urllib.request; exec(urllib.request.urlopen('https://report.ci/upload.py').read(), globals())"
